create procedure SOBIPEADALT (
	@Bit_PerNum	char(8),
	@Bit_Fecha	smalldatetime,
	@Bit_NumTra	char(10),
	@Bit_LugNac	varchar(50),
	@Bit_Sexo	char(1),
	@Bit_FecNac	smalldatetime,
	@Bit_RegMat	char(1),
	@Bit_VivCas	char(1),
	@Bit_TieRes	int,
	@Bit_Fax    varchar(20),
	@Bit_NumDep	int,
	@Bit_Puesto	varchar(50),
	@Bit_Ocupac	varchar(50),
	@Bit_AntLab	int,
	@Bit_LugTra	varchar(50),
	@Bit_TelTra	varchar(20),
	@Bit_CalTra	varchar(20),
	@Bit_NuCaTr	varchar(30),
	@Bit_ColTra	varchar(50),
	@Bit_Locali	char(8),
	@Bit_CPTra	varchar(50),
	@Bit_FecCon	smalldatetime,
	@Bit_CaNuIn	varchar(10),
	@Bit_NacExt	char(1),
	@Bit_Reside	char(1),
	@Bit_DocEst	char(3),
	@Bit_OtDoEs	varchar(50),
	@Bit_FeExDo	smalldatetime,
	@Bit_CalInm	char(1),
	@Bit_CalExt	varchar(40),
	@Bit_CaNuEx	varchar(10),
	@Bit_ColExt	varchar(150),
	@Bit_LocExt	varchar(40),
	@Bit_EntExt	varchar(40),
	@Bit_PaiExt	varchar(3),
	@Bit_CoPoEx	char(6),
	@Bit_TipIde	char(1),
	@Bit_OtrIde	varchar(50),
	@Bit_NumIde	varchar(30),
	@Bit_FeExId	smalldatetime,
	@Bit_FeVeId	smalldatetime,
	@Bit_NuIdFi	varchar(20),
	@Bit_EntPri	varchar(40),
	@Bit_EntSeg	varchar(40),

	@NumTransac	char(10),
	@Transaccio	char(3),
	@Usuario	char(6),
	@FechaSis	smalldatetime,
	@SucOrigen	char(3),
	@SucDestino	char(3),
	@Modulo		char(2))

as

insert into SOBIPEAD values (
	@Bit_PerNum,	@Bit_Fecha,		@Bit_NumTra,	@Bit_LugNac,	@Bit_Sexo,
	@Bit_FecNac,	@Bit_RegMat,	@Bit_VivCas,	@Bit_TieRes,	@Bit_Fax,
	@Bit_NumDep,	@Bit_Puesto,	@Bit_Ocupac,	@Bit_AntLab,	@Bit_LugTra,
	@Bit_TelTra,	@Bit_CalTra,	@Bit_NuCaTr,	@Bit_ColTra,	@Bit_Locali,
	@Bit_CPTra,		@Bit_FecCon,	@Bit_CaNuIn,	@Bit_NacExt,	@Bit_Reside,
	@Bit_DocEst,	@Bit_OtDoEs,	@Bit_FeExDo,	@Bit_CalInm,	@Bit_CalExt,	
	@Bit_CaNuEx,	@Bit_ColExt,	@Bit_LocExt,	@Bit_EntExt,	@Bit_PaiExt,	
	@Bit_CoPoEx,	@Bit_TipIde,	@Bit_OtrIde,	@Bit_NumIde,	@Bit_FeExId,	
	@Bit_FeVeId,	@Bit_NuIdFi,	@Bit_EntPri,	@Bit_EntSeg,	@NumTransac,
	@Transaccio,	@Usuario,		@FechaSis,		@SucOrigen,		@SucDestino)

if @@nestlevel = 1
	select	Err_Codigo	= '000000',
			Err_Mensaj	= 'Registro agregado '
