name: 🔍 SQLCHECKER

on:
  workflow_dispatch:
    inputs:
      rama_a_validar:
        description: '🌿 Nombre de la rama a validar (ej: test1, feature/nueva-consulta)'
        required: true
        type: string

permissions:
  contents: read
  actions: read        # Para artifacts

jobs:
  revision-sql:
    uses: regional-arq-calidad/sqlcheck-pruebas/.github/workflows/sql_check.yml@git-action
    with:
      rama_a_validar: ${{ github.event.inputs.rama_a_validar }}
    secrets: inherit